"use client";

import { motion } from "framer-motion";
import { Card, CardContent } from "@/components/ui/card";
import { Brain, Map, Download, Coins } from "lucide-react";

const features = [
  {
    icon: Brain,
    title: "AI-Powered Itineraries",
    description: "Get personalized travel plans generated by advanced AI that understands your preferences, budget, and travel style."
  },
  {
    icon: Map,
    title: "Real-Time Interactive Maps",
    description: "Explore your destinations with live maps, find nearby attractions, restaurants, and get real-time navigation assistance."
  },
  {
    icon: Download,
    title: "Downloadable PDF Plans",
    description: "Export your complete itinerary as a beautiful PDF to access offline, share with friends, or print for your journey."
  },
  {
    icon: Coins,
    title: "Flexible Credit System",
    description: "Pay only for what you use with our credit-based system. Start free and upgrade as your travel planning needs grow."
  }
];

export function FeaturesSection() {
  return (
    <section className="py-24 px-4 sm:px-6 lg:px-8 bg-white">
      <div className="max-w-7xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <h2 className="text-4xl sm:text-5xl font-bold text-gray-900 mb-6">
            Everything You Need to Plan
          </h2>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto">
            GoRoam combines cutting-edge AI technology with user-friendly design to make travel planning effortless and enjoyable.
          </p>
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          {features.map((feature, index) => (
            <motion.div
              key={feature.title}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8, delay: index * 0.1 }}
              viewport={{ once: true }}
            >
              <Card className="h-full border border-gray-100 hover:border-orange-200 transition-colors duration-300 shadow-sm hover:shadow-md">
                <CardContent className="p-8 text-center">
                  <div className="inline-flex items-center justify-center w-16 h-16 bg-orange-50 text-orange-500 rounded-2xl mb-6">
                    <feature.icon className="h-8 w-8" />
                  </div>
                  <h3 className="text-xl font-semibold text-gray-900 mb-4">
                    {feature.title}
                  </h3>
                  <p className="text-gray-600 leading-relaxed">
                    {feature.description}
                  </p>
                </CardContent>
              </Card>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
} 