"use client";

import { motion, useInView, useReducedMotion, useScroll, useSpring, useTransform } from "framer-motion";
import { ArrowUp, ArrowUpRight, Instagram, Linkedin, Lock, Mail, ShieldCheck, Shield, Twitter, Youtube, type LucideIcon } from "@/components/site/icons";
import Link from "next/link";
import { useSession } from "next-auth/react";
import { useRef } from "react";
import { getLenis } from "@/components/motion/smooth-scroll";
import { COMPANY, activeSocials, type SocialId } from "@/lib/company";
import { clockIn, useNow } from "@/lib/use-clock";
import { Logo } from "./logo";
import { TripPrompt } from "./trip-prompt";

const ease = [0.16, 1, 0.3, 1] as const;

/* -------------------------------------------------------------------------- */
/*                                   Columns                                  */
/* -------------------------------------------------------------------------- */

const COLUMNS = [
  {
    title: "Product",
    links: [
      { label: "Plan a trip", href: "/dashboard" },
      { label: "Trip gallery", href: "/itineraries" },
      { label: "How it works", href: "/#how" },
      { label: "Pricing", href: "/#pricing" },
    ],
  },
  {
    // Kept to a short, hand-picked list: the full guide data is too heavy to ship in every page's footer.
    title: "Destinations",
    links: [
      { label: "Goa", href: "/destinations/goa" },
      { label: "Jaipur", href: "/destinations/jaipur" },
      { label: "Udaipur", href: "/destinations/udaipur" },
      { label: "Kerala", href: "/destinations/kerala" },
      { label: "Ladakh", href: "/destinations/ladakh" },
      { label: "All guides", href: "/destinations" },
    ],
  },
  {
    title: "Company",
    links: [
      { label: "About", href: "/about" },
      { label: "Contact", href: "/contact" },
      { label: "FAQ", href: "/#faq" },
      { label: "Sign in", href: "/auth" },
    ],
  },
  {
    title: "Legal",
    links: [
      { label: "Terms of service", href: "/terms" },
      { label: "Privacy policy", href: "/privacy" },
      { label: "Refund policy", href: "/refunds" },
      { label: "Cookies & analytics", href: "/privacy#analytics" },
    ],
  },
];

/** The promises that matter before anyone pays. */
const TRUST: { icon: LucideIcon; title: string; body: string }[] = [
  { icon: ShieldCheck, title: "30-day money-back guarantee", body: "Email us and we refund it in full." },
  { icon: Lock, title: "Secure checkout by Dodo Payments", body: "Cards, UPI and local methods." },
  { icon: Shield, title: "Your data stays yours", body: "We never sell it, to anyone." },
];

const SOCIAL_ICONS: Record<SocialId, LucideIcon> = { x: Twitter, instagram: Instagram, youtube: Youtube, linkedin: Linkedin };

/* -------------------------------------------------------------------------- */
/*                               Harbour plate                                */
/* -------------------------------------------------------------------------- */

/** The plate's line colour: a dim sea-teal, so the harbour reads as quiet texture. */
const PLATE_LINE = "#5E8790";
/** The wordmark's: the theme's brass, like gilt lettering catching the moon. */
const WORDMARK = "#E9C27C";
const PLATE_BG = "#0A1C27";

/** A harbour ferry in the plate's engraved style, bow to the right. */
function Ferry() {
  return (
    <g stroke={PLATE_LINE} strokeWidth={1.1} strokeLinejoin="round">
      <path d="M-62 0H60L50 13H-54Z" fill={PLATE_BG} />
      <path d="M-58 4H56M-56 8H53" strokeWidth={0.8} />
      <path d="M-46 -15H42V0H-46Z" fill={PLATE_BG} />
      <path d="M-42 -9H38" strokeWidth={0.8} strokeDasharray="3 2.4" />
      <path d="M-28 -26H24V-15H-28Z" fill={PLATE_BG} />
      <path d="M-24 -21H20" strokeWidth={0.8} strokeDasharray="2.6 2.2" />
      <path d="M2 -38H12V-26H2Z" fill={PLATE_BG} />
      <path d="M4 -36V-27M7 -36V-27M10 -36V-27" strokeWidth={0.7} />
      {/* Wake */}
      <path d="M-66 12q-30 3 -70 1M-64 16q-40 4 -96 2M-60 20q-30 2 -60 1" strokeWidth={0.8} fill="none" />
    </g>
  );
}

/** A small sloop with hatched sails. */
function Sailboat() {
  return (
    <g stroke={PLATE_LINE} strokeWidth={1.1} strokeLinejoin="round">
      <path d="M-30 0H32L24 9H-24Z" fill={PLATE_BG} />
      <path d="M0 -2V-74" />
      <path d="M2 -70L30 -6H2Z" fill={PLATE_BG} />
      <path d="M-2 -64L-26 -6H-2Z" fill={PLATE_BG} />
      <path d="M6 -56V-6M10 -46V-6M14 -38V-6M18 -28V-6M22 -20V-6" strokeWidth={0.75} />
      <path d="M-6 -50V-6M-10 -40V-6M-14 -30V-6" strokeWidth={0.75} />
      <path d="M-34 12q20 3 70 0" strokeWidth={0.8} fill="none" />
    </g>
  );
}

/**
 * The footer's closing plate: Sydney Harbour by moonlight, engraved as dim teal
 * lines in the footer's ink, under a gilt "GoRoam". The plate is a static SVG
 * (generated by scripts/art/harbour-engraving.mjs); two ferries and a sailboat
 * move over it. It inks in from the left on view.
 */
function HarbourPlate() {
  const ref = useRef<HTMLDivElement>(null);
  const inView = useInView(ref, { once: true, amount: 0.25 });
  const reduce = useReducedMotion();
  // The wordmark rises from behind the harbour as the plate scrolls into view.
  const { scrollYProgress } = useScroll({ target: ref, offset: ["start end", "end end"] });
  const rise = useTransform(scrollYProgress, [0, 0.8], reduce ? [0, 0] : [90, 0]);
  return (
    <div ref={ref} className="relative border-t border-paper/10 pt-12 sm:pt-16">
      <motion.div
        initial={reduce ? false : { clipPath: "inset(0 100% 0 0)" }}
        animate={inView ? { clipPath: "inset(0 0% 0 0)" } : undefined}
        transition={{ duration: 2.4, ease }}
        className="relative aspect-[12/5] overflow-hidden sm:aspect-[3/1]"
      >
        {/* Behind the plate: a giant gilt-engraved "GoRoam", its feet tucked behind the city and the water. */}
        <svg viewBox="0 0 2400 800" preserveAspectRatio="xMidYMid slice" className="pointer-events-none absolute inset-0 size-full" aria-hidden>
          <defs>
            {/* Gilt at the top, fading as the letters sink behind the city. */}
            <linearGradient id="wordmark-gilt" x1="0" y1="0" x2="0" y2="1">
              <stop offset="0" stopColor={WORDMARK} stopOpacity={0.85} />
              <stop offset="0.6" stopColor={WORDMARK} stopOpacity={0.32} />
              <stop offset="1" stopColor={WORDMARK} stopOpacity={0.06} />
            </linearGradient>
          </defs>
          <motion.g style={{ y: rise }}>
            <text
              x={1212}
              y={532}
              textAnchor="middle"
              textLength={1700}
              lengthAdjust="spacingAndGlyphs"
              fontSize={540}
              style={{ fontFamily: "var(--font-space), sans-serif", fontWeight: 600, letterSpacing: "-0.04em" }}
            >
              {/* An offset outline first, like the shadow line of an engraved letter. */}
              <tspan fill="none" stroke={WORDMARK} strokeWidth={1.2} strokeOpacity={0.22}>
                GoRoam
              </tspan>
            </text>
            <text
              x={1200}
              y={520}
              textAnchor="middle"
              textLength={1700}
              lengthAdjust="spacingAndGlyphs"
              fontSize={540}
              fill="url(#wordmark-gilt)"
              stroke={WORDMARK}
              strokeOpacity={0.7}
              strokeWidth={1.4}
              style={{ fontFamily: "var(--font-space), sans-serif", fontWeight: 600, letterSpacing: "-0.04em" }}
            >
              GoRoam
            </text>
          </motion.g>
        </svg>
        {/* eslint-disable-next-line @next/next/no-img-element -- a static vector plate, already sized */}
        <img
          src="/art/harbour-engraving.svg"
          alt="Sydney Harbour by moonlight, engraved: the Harbour Bridge, the Opera House and the city skyline, with Fort Denison and trees on both shores."
          loading="lazy"
          decoding="async"
          width={2400}
          height={800}
          className="absolute inset-0 size-full object-cover"
        />
        {!reduce && (
          <svg viewBox="0 0 2400 800" preserveAspectRatio="xMidYMid slice" className="pointer-events-none absolute inset-0 size-full" aria-hidden>
            <g className="plate-ferry-a">
              <g transform="translate(520 676)">
                <Ferry />
              </g>
            </g>
            <g className="plate-ferry-b">
              <g transform="translate(1500 734) scale(-1.25 1.25)">
                <Ferry />
              </g>
            </g>
            <g transform="translate(1010 712)">
              <g className="plate-bob">
                <Sailboat />
              </g>
            </g>
          </svg>
        )}
      </motion.div>
    </div>
  );
}

/* -------------------------------------------------------------------------- */
/*                                 Back to top                                */
/* -------------------------------------------------------------------------- */

function BackToTop() {
  const { scrollYProgress } = useScroll();
  const progress = useSpring(scrollYProgress, { stiffness: 120, damping: 24 });
  const top = () => {
    const lenis = getLenis();
    if (lenis) lenis.scrollTo(0, { duration: 1.6 });
    else window.scrollTo({ top: 0, behavior: "smooth" });
  };
  return (
    <button type="button" onClick={top} aria-label="Back to top" className="group relative grid size-14 place-items-center rounded-full text-paper transition-colors hover:text-ink">
      <span className="absolute inset-1 rounded-full bg-paper/[0.06] transition-colors duration-500 group-hover:bg-paper" />
      <svg viewBox="0 0 56 56" className="absolute inset-0 -rotate-90">
        <circle cx="28" cy="28" r="26" fill="none" stroke="currentColor" strokeOpacity={0.15} strokeWidth={1.5} />
        <motion.circle cx="28" cy="28" r="26" fill="none" stroke="#3CCFBC" strokeWidth={1.5} strokeLinecap="round" style={{ pathLength: progress }} />
      </svg>
      <ArrowUp className="relative size-4 transition-transform duration-500 group-hover:-translate-y-0.5" />
    </button>
  );
}

/* -------------------------------------------------------------------------- */
/*                                   Footer                                   */
/* -------------------------------------------------------------------------- */

/** "Made in Gurgaon, India · 9:41 PM there now": a person and a place behind the product. */
function MadeIn() {
  const now = useNow();
  return (
    <p className="mt-7 inline-flex items-center gap-2.5 rounded-full bg-paper/[0.05] px-3.5 py-2 text-sm text-paper/70 ring-1 ring-inset ring-paper/10">
      <span aria-hidden className="size-1.5 rounded-full bg-brand-2" />
      <span>
        Made in {COMPANY.city}
        {now && (
          <>
            {" "}
            · <span className="tabular-nums text-paper/90">{clockIn(COMPANY.timeZone, now, true)}</span> there now
          </>
        )}
      </span>
    </p>
  );
}

/** Where to next: the planner, one sentence away, on every page that doesn't already end with it. */
function ClosingPrompt() {
  return (
    <div className="container-x relative">
      <div className="grid items-end gap-8 border-b border-paper/10 py-16 sm:py-20 lg:grid-cols-12 lg:gap-12">
        <div className="lg:col-span-6">
          <p className="eyebrow text-brand-2">Your next trip</p>
          <h2 className="display mt-4 text-[clamp(2rem,4vw,3.25rem)] leading-[1.04]">
            Where to <span className="accent">next?</span>
          </h2>
          <p className="mt-4 max-w-md leading-relaxed text-paper/60">Type a place, or a feeling. Your first trip plan is free, and it takes about a minute.</p>
        </div>
        <TripPrompt tone="glass" className="lg:col-span-6" />
      </div>
    </div>
  );
}

/** The site's foot. `cta` adds the planner prompt on top, for pages that don't already close with one. */
export function SiteFooter({ cta = true }: { cta?: boolean }) {
  const socials = activeSocials();
  const { status } = useSession();
  const signedIn = status === "authenticated";
  return (
    <footer className="relative overflow-hidden bg-ink text-paper">
      {/* Rails, as on the rest of the landing page */}
      <div aria-hidden className="pointer-events-none absolute inset-0 hidden md:block">
        <div className="container-x relative h-full">
          <span className="absolute inset-y-0 w-px bg-paper/[0.05]" style={{ left: "max(6px, calc(clamp(1rem,4vw,3rem) - 1.25rem))" }} />
          <span className="absolute inset-y-0 w-px bg-paper/[0.05]" style={{ right: "max(6px, calc(clamp(1rem,4vw,3rem) - 1.25rem))" }} />
        </div>
      </div>

      {cta && <ClosingPrompt />}

      <div className="container-x relative grid gap-14 pb-12 pt-16 sm:pt-20 lg:grid-cols-12">
        <div className="lg:col-span-4">
          <Logo tone="paper" />
          <p className="mt-6 max-w-sm text-[1.0625rem] leading-relaxed text-paper/65">
            AI-planned itineraries for curious travellers: real places, honest budgets and well-paced days.
          </p>
          <MadeIn />
          <div className="mt-6 flex flex-wrap items-center gap-2">
            {socials.map((s) => {
              const Icon = SOCIAL_ICONS[s.id];
              return (
                <a
                  key={s.id}
                  href={s.href}
                  target="_blank"
                  rel="noreferrer"
                  aria-label={`GoRoam on ${s.label}`}
                  className="grid size-11 place-items-center rounded-full text-paper/75 ring-1 ring-inset ring-paper/15 transition-colors duration-300 hover:bg-paper hover:text-ink"
                >
                  <Icon className="size-4" />
                </a>
              );
            })}
            <a
              href={`mailto:${COMPANY.email}`}
              className="inline-flex h-11 items-center gap-2 rounded-full px-4 text-sm text-paper/75 ring-1 ring-inset ring-paper/15 transition-colors duration-300 hover:bg-paper hover:text-ink"
            >
              <Mail className="size-4" /> {COMPANY.email}
            </a>
          </div>
        </div>
        <nav aria-label="Footer" className="grid grid-cols-2 gap-x-8 gap-y-10 sm:grid-cols-4 lg:col-span-8 lg:pl-8">
          {COLUMNS.map((col, c) => (
            <motion.div key={col.title} initial={{ opacity: 0, y: 14 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.4 }} transition={{ duration: 0.8, ease, delay: c * 0.06 }}>
              <p className="eyebrow text-paper/45">{col.title}</p>
              <ul className="mt-6 space-y-3.5">
                {col.links.map((l) => {
                  const link = l.href === "/auth" && signedIn ? { label: "Dashboard", href: "/dashboard" } : l;
                  return (
                    <li key={l.label}>
                      <Link href={link.href} className="group relative inline-flex items-center gap-1.5 text-paper/80 transition-colors hover:text-paper">
                        <span className="relative">
                          {link.label}
                          <span className="absolute -bottom-0.5 left-0 h-px w-full origin-right scale-x-0 bg-brand-2 transition-transform duration-500 ease-out-expo group-hover:origin-left group-hover:scale-x-100" />
                        </span>
                        <ArrowUpRight className="size-3.5 -translate-x-1 opacity-0 transition-all duration-500 ease-out-expo group-hover:translate-x-0 group-hover:opacity-100" />
                      </Link>
                    </li>
                  );
                })}
              </ul>
            </motion.div>
          ))}
        </nav>
      </div>

      {/* What you can count on */}
      <div className="container-x relative">
        <ul className="grid gap-5 border-t border-paper/10 py-8 sm:grid-cols-3 sm:gap-6">
          {TRUST.map((t) => (
            <li key={t.title} className="flex items-center gap-3.5">
              <span className="grid size-10 shrink-0 place-items-center rounded-full bg-paper/[0.06] text-brand-2 ring-1 ring-inset ring-paper/10">
                <t.icon className="size-[18px]" />
              </span>
              <span className="min-w-0">
                <span className="block text-sm text-paper/85">{t.title}</span>
                <span className="mt-0.5 block text-xs text-paper/45">{t.body}</span>
              </span>
            </li>
          ))}
        </ul>
      </div>

      <div className="container-x relative">
        <div className="flex flex-col gap-5 border-t border-paper/10 py-7 text-sm text-paper/50 sm:flex-row sm:items-center sm:justify-between">
          <div className="space-y-1.5">
            <p>© {new Date().getFullYear()} GoRoam. All rights reserved.</p>
            <p className="text-xs leading-relaxed text-paper/45">
              Operated by {COMPANY.operator} · {COMPANY.location} · Payments processed by Dodo Payments, our merchant of record.
            </p>
          </div>
          <BackToTop />
        </div>
      </div>

      <HarbourPlate />
    </footer>
  );
}
