"use client";

import { motion, useInView, useReducedMotion, useScroll, useSpring, useTransform } from "framer-motion";
import { ArrowUp, ArrowUpRight, Instagram, Linkedin, Mail, Twitter, Youtube, type LucideIcon } from "@/components/site/icons";
import Link from "next/link";
import { useRef } from "react";
import { getLenis } from "@/components/motion/smooth-scroll";
import { COMPANY, activeSocials, type SocialId } from "@/lib/company";
import { Logo } from "./logo";

const ease = [0.16, 1, 0.3, 1] as const;

/* -------------------------------------------------------------------------- */
/*                                   Columns                                  */
/* -------------------------------------------------------------------------- */

const COLUMNS = [
  {
    title: "Product",
    links: [
      { label: "Plan a trip", href: "/dashboard" },
      { label: "Trip gallery", href: "/itineraries" },
      { label: "Destination guides", href: "/destinations" },
      { label: "How it works", href: "/#how" },
      { label: "Pricing", href: "/#pricing" },
    ],
  },
  {
    title: "Company",
    links: [
      { label: "About", href: "/about" },
      { label: "Contact", href: "/contact" },
      { label: "FAQ", href: "/#faq" },
      { label: "Sign in", href: "/auth" },
    ],
  },
  {
    title: "Legal",
    links: [
      { label: "Terms of service", href: "/terms" },
      { label: "Privacy policy", href: "/privacy" },
      { label: "Refund policy", href: "/refunds" },
      { label: "Cookies & analytics", href: "/privacy#analytics" },
    ],
  },
];

const SOCIAL_ICONS: Record<SocialId, LucideIcon> = { x: Twitter, instagram: Instagram, youtube: Youtube, linkedin: Linkedin };

/* -------------------------------------------------------------------------- */
/*                               Harbour plate                                */
/* -------------------------------------------------------------------------- */

/** The plate's line colour: a dim sea-teal, so the harbour reads as quiet texture. */
const PLATE_LINE = "#5E8790";
/** The wordmark's: the theme's warm gold, like gilt engraved lettering. */
const WORDMARK = "#FFC876";
const PLATE_BG = "#0A1C27";

/** A harbour ferry in the plate's engraved style, bow to the right. */
function Ferry() {
  return (
    <g stroke={PLATE_LINE} strokeWidth={1.1} strokeLinejoin="round">
      <path d="M-62 0H60L50 13H-54Z" fill={PLATE_BG} />
      <path d="M-58 4H56M-56 8H53" strokeWidth={0.8} />
      <path d="M-46 -15H42V0H-46Z" fill={PLATE_BG} />
      <path d="M-42 -9H38" strokeWidth={0.8} strokeDasharray="3 2.4" />
      <path d="M-28 -26H24V-15H-28Z" fill={PLATE_BG} />
      <path d="M-24 -21H20" strokeWidth={0.8} strokeDasharray="2.6 2.2" />
      <path d="M2 -38H12V-26H2Z" fill={PLATE_BG} />
      <path d="M4 -36V-27M7 -36V-27M10 -36V-27" strokeWidth={0.7} />
      {/* Wake */}
      <path d="M-66 12q-30 3 -70 1M-64 16q-40 4 -96 2M-60 20q-30 2 -60 1" strokeWidth={0.8} fill="none" />
    </g>
  );
}

/** A small sloop with hatched sails. */
function Sailboat() {
  return (
    <g stroke={PLATE_LINE} strokeWidth={1.1} strokeLinejoin="round">
      <path d="M-30 0H32L24 9H-24Z" fill={PLATE_BG} />
      <path d="M0 -2V-74" />
      <path d="M2 -70L30 -6H2Z" fill={PLATE_BG} />
      <path d="M-2 -64L-26 -6H-2Z" fill={PLATE_BG} />
      <path d="M6 -56V-6M10 -46V-6M14 -38V-6M18 -28V-6M22 -20V-6" strokeWidth={0.75} />
      <path d="M-6 -50V-6M-10 -40V-6M-14 -30V-6" strokeWidth={0.75} />
      <path d="M-34 12q20 3 70 0" strokeWidth={0.8} fill="none" />
    </g>
  );
}

/**
 * The footer's closing plate: Sydney Harbour by moonlight, engraved as dim teal
 * lines in the footer's ink, under a gilt "GoRoam". The plate is a static SVG
 * (generated by scripts/art/harbour-engraving.mjs); ferries, a sailboat and
 * glints on the moon's path move over it. It inks in from the left on view.
 */
function HarbourPlate() {
  const ref = useRef<HTMLDivElement>(null);
  const inView = useInView(ref, { once: true, amount: 0.25 });
  const reduce = useReducedMotion();
  // The wordmark rises from behind the harbour as the plate scrolls into view.
  const { scrollYProgress } = useScroll({ target: ref, offset: ["start end", "end end"] });
  const rise = useTransform(scrollYProgress, [0, 0.8], reduce ? [0, 0] : [90, 0]);
  const glints = [
    [1300, 650, 16],
    [1560, 676, 20],
    [1640, 708, 24],
    [760, 690, 18],
  ];
  return (
    <div ref={ref} className="relative border-t border-paper/10 pt-12 sm:pt-16">
      <motion.div
        initial={reduce ? false : { clipPath: "inset(0 100% 0 0)" }}
        animate={inView ? { clipPath: "inset(0 0% 0 0)" } : undefined}
        transition={{ duration: 2.4, ease }}
        className="relative aspect-[12/5] overflow-hidden sm:aspect-[3/1]"
      >
        {/* Behind the plate: a giant gilt-engraved "GoRoam", its feet tucked behind the city and the water. */}
        <svg viewBox="0 0 2400 800" preserveAspectRatio="xMidYMid slice" className="pointer-events-none absolute inset-0 size-full" aria-hidden>
          <defs>
            <pattern id="wordmark-hatch" width="4.5" height="4.5" patternUnits="userSpaceOnUse">
              {/* A faint gilt wash under the hairlines keeps the letters golden even when they're small. */}
              <rect width="4.5" height="4.5" fill={WORDMARK} fillOpacity={0.14} />
              <path d="M0 2.25H4.5" stroke={WORDMARK} strokeWidth={1.1} />
            </pattern>
          </defs>
          <motion.g style={{ y: rise }}>
            <text
              x={1212}
              y={532}
              textAnchor="middle"
              textLength={1700}
              lengthAdjust="spacingAndGlyphs"
              fontSize={540}
              style={{ fontFamily: "var(--font-space), sans-serif", fontWeight: 600, letterSpacing: "-0.04em" }}
            >
              {/* An offset outline first, like the shadow line of an engraved letter. */}
              <tspan fill="none" stroke={WORDMARK} strokeWidth={1.2} strokeOpacity={0.35}>
                GoRoam
              </tspan>
            </text>
            <text
              x={1200}
              y={520}
              textAnchor="middle"
              textLength={1700}
              lengthAdjust="spacingAndGlyphs"
              fontSize={540}
              fill="url(#wordmark-hatch)"
              stroke={WORDMARK}
              strokeWidth={1.8}
              style={{ fontFamily: "var(--font-space), sans-serif", fontWeight: 600, letterSpacing: "-0.04em" }}
            >
              GoRoam
            </text>
          </motion.g>
        </svg>
        {/* eslint-disable-next-line @next/next/no-img-element -- a static vector plate, already sized */}
        <img
          src="/art/harbour-engraving.svg"
          alt="Sydney Harbour by moonlight, engraved: the Harbour Bridge, the Opera House and the city skyline, with Fort Denison and trees on both shores."
          loading="lazy"
          decoding="async"
          width={2400}
          height={800}
          className="absolute inset-0 size-full object-cover"
        />
        {!reduce && (
          <svg viewBox="0 0 2400 800" preserveAspectRatio="xMidYMid slice" className="pointer-events-none absolute inset-0 size-full" aria-hidden>
            <g className="plate-ferry-a">
              <g transform="translate(520 676)">
                <Ferry />
              </g>
            </g>
            <g className="plate-ferry-b">
              <g transform="translate(1500 734) scale(-1.25 1.25)">
                <Ferry />
              </g>
            </g>
            <g transform="translate(1010 712)">
              <g className="plate-bob">
                <Sailboat />
              </g>
            </g>
            {glints.map(([x, y, l], i) => (
              <path key={i} d={`M${x} ${y}h${l}`} stroke={PLATE_LINE} strokeWidth={1.4} strokeLinecap="round" className="plate-glint" style={{ animationDelay: `${i * 0.7}s` }} />
            ))}
          </svg>
        )}
      </motion.div>
    </div>
  );
}

/* -------------------------------------------------------------------------- */
/*                                 Back to top                                */
/* -------------------------------------------------------------------------- */

function BackToTop() {
  const { scrollYProgress } = useScroll();
  const progress = useSpring(scrollYProgress, { stiffness: 120, damping: 24 });
  const top = () => {
    const lenis = getLenis();
    if (lenis) lenis.scrollTo(0, { duration: 1.6 });
    else window.scrollTo({ top: 0, behavior: "smooth" });
  };
  return (
    <button type="button" onClick={top} aria-label="Back to top" className="group relative grid size-14 place-items-center rounded-full text-paper transition-colors hover:text-ink">
      <span className="absolute inset-1 rounded-full bg-paper/[0.06] transition-colors duration-500 group-hover:bg-paper" />
      <svg viewBox="0 0 56 56" className="absolute inset-0 -rotate-90">
        <circle cx="28" cy="28" r="26" fill="none" stroke="currentColor" strokeOpacity={0.15} strokeWidth={1.5} />
        <motion.circle cx="28" cy="28" r="26" fill="none" stroke="#3CCFBC" strokeWidth={1.5} strokeLinecap="round" style={{ pathLength: progress }} />
      </svg>
      <ArrowUp className="relative size-4 transition-transform duration-500 group-hover:-translate-y-0.5" />
    </button>
  );
}

/* -------------------------------------------------------------------------- */
/*                                   Footer                                   */
/* -------------------------------------------------------------------------- */

export function SiteFooter() {
  const socials = activeSocials();
  return (
    <footer className="relative overflow-hidden bg-ink text-paper">
      {/* Rails, as on the rest of the landing page */}
      <div aria-hidden className="pointer-events-none absolute inset-0 hidden md:block">
        <div className="container-x relative h-full">
          <span className="absolute inset-y-0 w-px bg-paper/[0.05]" style={{ left: "max(6px, calc(clamp(1rem,4vw,3rem) - 1.25rem))" }} />
          <span className="absolute inset-y-0 w-px bg-paper/[0.05]" style={{ right: "max(6px, calc(clamp(1rem,4vw,3rem) - 1.25rem))" }} />
        </div>
      </div>

      <div className="container-x relative grid gap-14 pb-14 pt-20 sm:pt-24 lg:grid-cols-12">
        <div className="lg:col-span-5">
          <Logo tone="paper" />
          <p className="mt-6 max-w-sm text-[1.0625rem] leading-relaxed text-paper/65">
            AI-planned itineraries for curious travellers: real places, honest budgets and well-paced days.
          </p>
          <div className="mt-8 flex flex-wrap items-center gap-2">
            {socials.map((s) => {
              const Icon = SOCIAL_ICONS[s.id];
              return (
                <a
                  key={s.id}
                  href={s.href}
                  target="_blank"
                  rel="noreferrer"
                  aria-label={`GoRoam on ${s.label}`}
                  className="grid size-11 place-items-center rounded-full text-paper/75 ring-1 ring-inset ring-paper/15 transition-colors duration-300 hover:bg-paper hover:text-ink"
                >
                  <Icon className="size-4" />
                </a>
              );
            })}
            <a
              href={`mailto:${COMPANY.email}`}
              className="inline-flex h-11 items-center gap-2 rounded-full px-4 text-sm text-paper/75 ring-1 ring-inset ring-paper/15 transition-colors duration-300 hover:bg-paper hover:text-ink"
            >
              <Mail className="size-4" /> {COMPANY.email}
            </a>
          </div>
        </div>
        <div className="grid grid-cols-2 gap-10 sm:grid-cols-3 lg:col-span-6 lg:col-start-7">
          {COLUMNS.map((col, c) => (
            <motion.div key={col.title} initial={{ opacity: 0, y: 14 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.4 }} transition={{ duration: 0.8, ease, delay: c * 0.06 }}>
              <p className="eyebrow text-paper/45">{col.title}</p>
              <ul className="mt-6 space-y-3.5">
                {col.links.map((l) => (
                  <li key={l.label}>
                    <Link href={l.href} className="group relative inline-flex items-center gap-1.5 text-paper/80 transition-colors hover:text-paper">
                      <span className="relative">
                        {l.label}
                        <span className="absolute -bottom-0.5 left-0 h-px w-full origin-right scale-x-0 bg-brand-2 transition-transform duration-500 ease-out-expo group-hover:origin-left group-hover:scale-x-100" />
                      </span>
                      <ArrowUpRight className="size-3.5 -translate-x-1 opacity-0 transition-all duration-500 ease-out-expo group-hover:translate-x-0 group-hover:opacity-100" />
                    </Link>
                  </li>
                ))}
              </ul>
            </motion.div>
          ))}
        </div>
      </div>

      <div className="container-x relative">
        <div className="flex flex-col gap-5 border-t border-paper/10 py-7 text-sm text-paper/50 sm:flex-row sm:items-center sm:justify-between">
          <div className="space-y-1.5">
            <p>© {new Date().getFullYear()} GoRoam. All rights reserved.</p>
            <p className="text-xs leading-relaxed text-paper/45">
              Operated by {COMPANY.operator} · {COMPANY.location} · Payments processed by Dodo Payments, our merchant of record.
            </p>
          </div>
          <BackToTop />
        </div>
      </div>

      <HarbourPlate />
    </footer>
  );
}
